//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Commandes = new HashSet<Commande>();
        }
    
        public int NumArticle { get; set; }
        public string Designation { get; set; }
        public string PrixU { get; set; }
        public string stock { get; set; }
        public string photo { get; set; }
        public Nullable<int> RefCat { get; set; }
    
        public virtual ICollection<Commande> Commandes { get; set; }
        public virtual Categorie Categorie { get; set; }
    }
}
