//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class Categorie
    {
        public Categorie()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int RefCat { get; set; }
        public string NomCat { get; set; }
        public IEnumerable<Categorie> ListCategorie { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
    }
}
