//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int NumCmd { get; set; }
        public string DateCmd { get; set; }
        public Nullable<int> NumClient { get; set; }
        public Nullable<int> NumArticle { get; set; }
        public Nullable<int> QteArticle { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Client Client { get; set; }
    }
}
